### ISSUE TITLE
Fuente de familia Roboto no cargan

### ISSUE THREAD

**Issue by danieIabel** [zkreations/bison#16]
**Describa el error**
La fuente Roboto no esta cargando en la plantilla

**Comportamiento esperado**
La fuente "Roboto" debería de cargar tanto en escritorio como en móviles

**Comment by marcogiannini** [comment]
I noticed a strange behavior. Yesterday, after installing Roboto fonts on the pc, the problem had resolved (at least locally on my pc). This morning, although the Roboto fonts are installed on the pc, the font rendering is again incorrect.

**Comment by danieIabel** [comment]
I have already identified the problem, the Roboto font does not load in the template and tries to take it from the operating system, I will make the change.

**Comment by danieIabel** [comment]
Problema resuelto
