### ISSUE TITLE
In the main screen the thumbnails of the posts they are not loaded if hosted on external services

### ISSUE THREAD

**Issue by marcogiannini** [zkreations/bison#18]
In the main screen the thumbnails of the posts they are not loaded if hosted on external services.

Theme updated with latest changes to fix the problem of Roboto fonts not loading.

![erroreimmagini](https://user-images.githubusercontent.com/4943897/205730018-5d9d3c5f-e225-4f93-b24e-1e742f6e4251.png)

**Comment by danieIabel** [comment]
When the image is hosted on another server, Blogger delivers it via proxy, when this is not possible, it gets a url starting with "testonly" which is broken. This is a platform issue: https://support.google.com/blogger/thread/168179180?hl=en

Usually this resolves itself after a few minutes, but to avoid this you should upload your images to Blogger.
