### ISSUE TITLE
Segmentación de palabras al final de las líneas

### ISSUE THREAD

**Issue by ghost** [zkreations/bison#46]
**Describa el error**
En las entradas las palabras finales de muchas líneas seguidas se dividen en dos partes por un “ - ” al final de los renglones.

**Reproducir**
Pasos para poder reproducir el comportamiento, ejemplo:
1. Vaya a guionflojo.com
2. Haga clic en alguna entrada.
3. Fíjese en las palabras finales de cada línea.

**Comportamiento esperado**
Cómo en la mayoría de entradas de blogs con el texto alineado hacia la derecha, si la palabra final de alguna línea es demasiado larga, se debe pasar la palabra completa a la siguiente línea en vez de dividirse en dos partes con un "-" al final de la línea.

**Capturas de pantalla**
![Screenshot_20230129-224943_1](https://user-images.githubusercontent.com/108814257/215378163-2fba66ad-fe8e-49a7-95e1-eb2ddade7b5c.png)

**Contexto adicional (Opcional)**
El problema se logra apreciar más en dispositivos móviles ya que hay menos espacio y se segmentan más palabras.

**Comment by danieIabel** [comment]
La propiedad css que lo causa se llama `hyphens`. La razón por la cual he optado en implementarla en la plantilla, es porque en la version anterior, los usuarios reportaban que ocasionalmente aparecía un espacio en blanco que permitía hacer scroll horizontal en moviles.

Esto lo causaba el texto largo, cuando un texto es demasiado largo y no cabe en la misma linea, puede causar desbordamiento. Si desea deshabilitar esta propiedad agregue el siguiente código en Temas > Personalizar > Opciones avanzadas > Agregar CSS:

```css
body {
    hyphens: initial;
    -webkit-hyphens: initial;
}
```

**Comment by Jesed07** [comment]
> La propiedad css que lo causa se llama `hyphens`. La razón por la cual he optado en implementarla en la plantilla, es porque en la version anterior, los usuarios reportaban que ocasionalmente aparecía un espacio en blanco que permitía hacer scroll horizontal en moviles.
> 
> Esto lo causaba el texto largo, cuando un texto es demasiado largo y no cabe en la misma linea, puede causar desbordamiento. Si desea deshabilitar esta propiedad agregue el siguiente código en Temas > Personalizar > Opciones avanzadas > Agregar CSS:
> 
> ```css
> body {
>     hyphens: initial;
>     -webkit-hyphens: initial;
> }
> ```

Muchas

> La propiedad css que lo causa se llama `hyphens`. La razón por la cual he optado en implementarla en la plantilla, es porque en la version anterior, los usuarios reportaban que ocasionalmente aparecía un espacio en blanco que permitía hacer scroll horizontal en moviles.
> 
> Esto lo causaba el texto largo, cuando un texto es demasiado largo y no cabe en la misma linea, puede causar desbordamiento. Si desea deshabilitar esta propiedad agregue el siguiente código en Temas > Personalizar > Opciones avanzadas > Agregar CSS:
> 
> ```css
> body {
>     hyphens: initial;
>     -webkit-hyphens: initial;
> }
> ```

Muchas gracias. Entonces en caso de querer poner todo como estaba por algún problema solo tengo que eliminar el código CSS añadido, cierto?
