### ISSUE TITLE
p.sponsor no funciona

### ISSUE THREAD

**Issue by EleAsecas** [zkreations/bison#50]
**Describa el error**
Al añadir la variable p.sponsor y etiquetar una entrada con el valor correspondiente la etiqueta sigue apareciendo en la nube de etiquetas y ademas la entrada no esta marcada con el icono y el mensaje que indica que es patrocinada

**Reproducir**
Pasos para poder reproducir el comportamiento, ejemplo:
1. Abro el xml del blog
2. Añado <Variable name="p.sponsor" description="Sponsor label" type="string" value="sponsor"/> donde estás las demas variables p
3. Etiqueto cualquier entrada con la palabra "sponsor"
4. Ver error

**Comportamiento esperado**
Lo que pone en la documentación, que la etiqueta sponsor no aparezca en la nube de etiquetas y que la entrada quede marcada con el mensaje definido en t.sponsored
<Variable name="t.sponsored" description="Texto para indicar entrada patrocinada" type="string" value="Patrocinada"/>

**Escritorio (complete la siguiente información si aplica):**
 - SO: Steam OS 3.5.19 y Ubuntu 24.04 LTS
 - Navegador: Chrome
 - Versión: 129.0.6668.58

**Comment by danieIabel** [comment]
Que tal amigo, acabo de reproducir los pasos y obtengo el funcionamiento normal del tema. ¿Se aseguró de estar usando la version correcta? La version Gratuita (GPL)  no tiene esta función y no se puede añadir tampoco. Esta función pertenece a la version Premium.

**Comment by EleAsecas** [comment]
Vale, debe ser eso ya que yo simplemente copié el código de la plantilla blank.xml del repo ¿Como obtengo la versión Premium?

**Comment by danieIabel** [comment]
Se adquiere desde mi tienda amigo: https://store.zkreations.com/2022/11/bison.html
