### ISSUE TITLE
p.template no acepta todos los valores ofrecidos en la documentación

### ISSUE THREAD

**Issue by EleAsecas** [zkreations/bison#51]
**Describa el error**
Al modificar el valor p.template por cualquiera de los que se ven en la documentación muy poco surten efecto. Las combinaciones de ejemplo tampoco he conseguido hacerlas funcionar. Yo quiero usar el centered-hero-fixed concretamente, pero solo me aplica el hero.

**Reproducir**
Pasos para poder reproducir el comportamiento, ejemplo:
1. Abres el xml del blog
2. cambias el valor default por cualquiera de los ofrecidos
3. Vas a cualquier entrada.
4. Ocurre lo descrito arriba

**Comportamiento esperado**
Que aplicara la variable como corresponde para que las entradas se vean como se define en p.template

**Capturas de pantalla**
Si corresponde, agregue capturas de pantalla para ayudar a explicar su problema.

**Escritorio (complete la siguiente información si aplica):**
 - SO: Steam OS 3.5.19 y Ubuntu 24.04 LTS
 - Navegador: Chrome
 - Versión: 129.0.6668.58

**Comment by danieIabel** [comment]
Buenas tardes amigo. He reproducido los pasos y todo parece funcionar. Puede tratarse de la version que esta usando. La version GPL solo dispone del modo "hero". Todas las demás y las combinaciones posibles requieren del tema Premium. De igual forma este sistema de "post-template" ha sido re-escrito para la version 6 de este tema. Como ya no se usa el sistema actual, el nuevo no trae los mismos problemas que este.

**Comment by EleAsecas** [comment]
Vale, si ya lo tienes solucionado en la versión 6, me espero a que lo saques. Supongo que será para la versión Premium, te leo por la otra issue como puedo obtenerla. Gracias.
