### ISSUE TITLE
Sugerencia para la jerarquía del archivo del blog

### ISSUE THREAD

**Issue by EleAsecas** [zkreations/bison#53]
ESTO NO ES UN BUG. Dado que solo me deja reportar bugs, lo pongo por aquí.
Me gusta mucho esta plantilla y ya estás viendo que estoy a tope probando todo lo que leo en la documentación. Veo que llevas un tiempo sin trabajar en ella pero si me lees te animo a que continúes, no tengo mucho pero alguna donación puedo hacer.

Siguiendo con la sugerencia, me encantaría que en el widget de archivo cuando pones el modo jerárquico se comportara como hacen las plantillas por defecto de blogger que es que se contraen por año y deja abierto el año en curso y los titulos de las entradas del mes en curso. Te adjunto una captura:
![image](https://github.com/user-attachments/assets/25299725-8ba6-4b03-80e7-2ff05344549e)

Es que si no blogs que llevan mucho tiempo funcionando queda horriblemente largo y si lo quieres poner en la footbar ni te digo.

Yo he intentado hacer clases personalizadas y modificar la creacion del hierarchy para meter <span> que me permitiera hacerlo, pero despues de un par de horas no lo he conseguido y dado que recomiendas no meter javascript por nuestra cuenta, prefiero que sea una implementación tuya.

Nada más, Espero que vaya todo bien. Un saludo.

**Comment by danieIabel** [comment]
Buenas tardes amigo. Todas las sugerencias son bien recibidas y las tomo en cuenta para la futura version.

Actualmente si estoy trabajando en una version 6 de este tema. La version actual usa un sistema desactualizado para compilar el tema. Mientras que la nueva version se basa en hamlet, proyecto que puedes revisar en este repositorio: https://github.com/zkreations/hamlet

También puedes probar temas que ya hice basados en hamlet para que puedas experimentar un poco (son temas sencillos pero que dan una idea de lo que se puede esperar de futuras versiones):

https://github.com/zkreations/laertes
https://github.com/zkreations/basico

**Comment by EleAsecas** [comment]
El tema de Laertes es ciertamente bonito, me gusta mucho como quedan las tarjetas con el borde oscuro para dar profundidad aunque de momento voy a seguir con Bison. Espero la versión 6 con ganas.
