### ISSUE TITLE
El aviso por defecto de cookies de blogger nunca aparece

### ISSUE THREAD

**Issue by EleAsecas** [zkreations/bison#54]
**Describa el error**
He intentado personalizar el aviso de cookies siguiendo estos pasos: https://www.zkreations.com/2017/12/personalizar-aviso-cookies-blogger-css-javascript.html, pero nunca aparece. Con las plantillas de Blogger no hay problema.

**Reproducir**
1. He seguido los pasos de esta entrada:
https://www.zkreations.com/2017/12/personalizar-aviso-cookies-blogger-css-javascript.html
2. El aviso no llega a aparecer nunca ni poniendo ?gl=fr ni borrando los datos de navegación y reiniciando el navegador
3. He deshecho los pasos seguidos en la entrada a ver si podía ver el predeterminado y tampoco.
4. He cambiado momentáneamente a una plantilla de Blogger y ahí aparece el aviso sin problema.

**Comportamiento esperado**
Por temas legales, me gustaría que apareciese el anuncio de cookies y además poder modificar el estilo.

**Escritorio (complete la siguiente información si aplica):**
 - SO: Steam OS 3.5.19 (Linux KDE)
 - Navegador: Chrome y Firefox
 - Versión: [p. ej. 22, 99, etc]

**Contexto adicional (Opcional)**
También he intentado hacer un aviso de cookies desde 0 siguiendo estos pasos: https://www.monetizaconabrahan.es/2023/10/como-poner-aviso-de-cookies-en-blogger.html y tampoco ha habido suerte

**Comment by danieIabel** [comment]
Que tal amigo, este problema ya lo trate, es por el hack que puse en el footer para evitar cargar el código javascript de Blogger. Puede leer aquí como tratar eso: https://github.com/zkreations/bison/issues/13

Adicionalmente, esto ya no es necesario en las plantillas basadas en hamlet y esta totalmente corregido, tambien en la version 6
