### ISSUE TITLE
p.sponsored sigue mostrando la etiqueta en la nube de etiquetas

### ISSUE THREAD

**Issue by EleAsecas** [zkreations/bison#55]
**Describa el error**
Ya he actualizado la plantilla del blog a la versión premium, ahora marca bien las entradas con la etiqueta de sponsored, pero sigue mostrando la etiqueta sponsored en la nube de etiquetas. Ojo, en la las etiquetas de la propia entrada sí que la borra, pero en el widget de nube de etiquetas no.

**Reproducir**
Pasos para poder reproducir el comportamiento, ejemplo:
1. Edito el value de la variable p.sponsored y escribo "Patrocinado"
2. Etiqueto una entrada como "Patrocinado"
3. Voy al blog, veo que la entrada se ha marcado con un color de acento distinto y que cuando entro en ella no aparece la etiqueta "Patrocinado", sin embargo en el widgets de nube de etiquetas sí que aparece el label.

**Comportamiento esperado**
No sé si entendí mal la documentación, pero pensaba que el label también desaparecería del widget de nube de etiquetas. Al menos a mi me gustaría que lo hiciera.

**Capturas de pantalla**
![image](https://github.com/user-attachments/assets/edcfd3b7-04c7-43f1-92f7-fccbeca4bbd7)
![image](https://github.com/user-attachments/assets/91d3e010-732b-414c-8853-ab040714be09)

**Escritorio (complete la siguiente información si aplica):**
 - SO: Steam OS 3.5.19
 - Navegador: Chrome
 - Versión: 129.0.6668.89

**Comment by danieIabel** [comment]
Aclarado y solucionado por mensaje privado.
